apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: http-push-notifications
  
spec:
  type: bindings.http
  version: v1
  metadata:
  - name: url
    value: https://casvi-ntfns-dev.servicebus.windows.net/casvi-ntf-dev