version: '3.4'

services:
  daprworkflows:
    image: ${DOCKER_REGISTRY-}daprworkflows
    build:
      context: .
      dockerfile: Dockerfile
  daprworkflows-dapr:
    image: "daprio/daprd:1.11.2"
    network_mode: "service:daprworkflows"
    command: ["./daprd",
      "--app-id", "daprworkflows",
      "--app-port", "80",
      "--components-path", "/components",
      "--log-level", "debug",
      "--dapr-http-max-request-size","16"
      ]
    volumes:
      - "./dapr/components/:/components"
    depends_on:
      - daprworkflows